version: "3.9"
services:
  # Database MongoDB (persistence layer for the app and Unleash)
  database:
    container_name: "database"
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # Unleash (the feature toggle server)
  # unleash:
  #   depends_on:
  #     - database
  #   container_name: "unleash"
  #   image: "unleashorg/unleash-server"
  #   ports:
  #     - "4242:4242"
  #   environment:
  #     DATABASE_URI: "mongodb://root:example@database:27017/unleash"
  #     DATABASE_NAME: "unleash"
  #     DATABASE_SSL: "false"
  #     DATABASE_AUTH_SOURCE: "admin"
  #     DATABASE_SSL_VALIDATE: "false"
  #   healthcheck:
  #     test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
  #     interval: 1s
  #     timeout: 1m
  #     retries: 5
  #     start_period: 15s